project:
  type: website
  output-dir: docs

website:
  title: "UMD PhD student Hyeri's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Class.qmd
      - Working Paper.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/hye-ri-park-998009b4/
      - icon: github
        href: https://github.com/ellieP123/Personal_Webpage_ver.2
      - icon: gmail
        href: mailto:hpark100@umd.edu.zz
 
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Hyeri Park"

format:
  html:
    theme: minty
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#070707"
    linkcolor: "#6649C3"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

